includeSubdirs = True
encoding_format = "latin"
image_types = (".JPG", ".jpg", ".tif", ".tiff", ".hdr", ".exr", ".ufo", ".fpx")
video_types = (".MP4", ".mp4")
file_types = image_types + video_types
hdr_program = "franzis HDR projects"
panorama_program = "Hugin"
photographer = "Marco Volkert"
standard_kamera = "DMC-TZ101"
googlemaps_api_key = ""